//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchExternalProperty
    {
        public int ExternalPropertyId { get; set; }
        public long BatchId { get; set; }
        public string ExternalPropertyValue { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual ExternalProperty ExternalProperty { get; set; }
    }
}
