//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch()
        {
            this.BatchExternalProperties = new HashSet<BatchExternalProperty>();
            this.Documents = new HashSet<Document>();
            this.Pages = new HashSet<Page>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int WorkflowId { get; set; }
        public int BatchStatus { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Username { get; set; }
        public int BatchPages { get; set; }
        public bool IsAssignedAsDocument { get; set; }
    
        public virtual BatchAssignment BatchAssignment { get; set; }
        public virtual Workflow Workflow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchExternalProperty> BatchExternalProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages { get; set; }
    }
}
