//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComposedBarcodeConfiguration
    {
        public int Id { get; set; }
        public int InitialPosition { get; set; }
        public int FinalPosition { get; set; }
        public int ElementType { get; set; }
        public string Example { get; set; }
        public string ExtractedData { get; set; }
        public string BarcodeFormat { get; set; }
    }
}
