//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProdoctivityCaptureDBEntities : DbContext
    {
        public ProdoctivityCaptureDBEntities()
            : base("name=ProdoctivityCaptureDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ActiveInstanceService> ActiveInstanceServices { get; set; }
        public virtual DbSet<BatchAssignment> BatchAssignments { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<BatchExternalProperty> BatchExternalProperties { get; set; }
        public virtual DbSet<ComposedBarcodeConfiguration> ComposedBarcodeConfigurations { get; set; }
        public virtual DbSet<CustomReportConfiguration> CustomReportConfigurations { get; set; }
        public virtual DbSet<DocumentAssignment> DocumentAssignments { get; set; }
        public virtual DbSet<DocumentBarcodeMetadata> DocumentBarcodeMetadatas { get; set; }
        public virtual DbSet<DocumentComment> DocumentComments { get; set; }
        public virtual DbSet<DocumentQrMetadata> DocumentQrMetadatas { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentsSplitter> DocumentsSplitters { get; set; }
        public virtual DbSet<DocumentsUserAction> DocumentsUserActions { get; set; }
        public virtual DbSet<ExternalProperty> ExternalProperties { get; set; }
        public virtual DbSet<Index> Indices { get; set; }
        public virtual DbSet<InstanceConfiguration> InstanceConfigurations { get; set; }
        public virtual DbSet<LoginAudit> LoginAudits { get; set; }
        public virtual DbSet<PageQrMetadata> PageQrMetadatas { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<PaperSizeConfiguration> PaperSizeConfigurations { get; set; }
        public virtual DbSet<PixelTypeConfiguration> PixelTypeConfigurations { get; set; }
        public virtual DbSet<QueueManagementConfiguration> QueueManagementConfigurations { get; set; }
        public virtual DbSet<RoleScannerProfilesAssignment> RoleScannerProfilesAssignments { get; set; }
        public virtual DbSet<RolesSpecialPermission> RolesSpecialPermissions { get; set; }
        public virtual DbSet<RoleWorkflowAssignment> RoleWorkflowAssignments { get; set; }
        public virtual DbSet<ScannerProfile> ScannerProfiles { get; set; }
        public virtual DbSet<UserActionLog> UserActionLogs { get; set; }
        public virtual DbSet<Volume> Volumes { get; set; }
        public virtual DbSet<WebHookClient> WebHookClients { get; set; }
        public virtual DbSet<WorkflowDocumentTypeAssignment> WorkflowDocumentTypeAssignments { get; set; }
        public virtual DbSet<Workflow> Workflows { get; set; }
        public virtual DbSet<WorkflowSplitter> WorkflowSplitters { get; set; }
        public virtual DbSet<WorkflowStepsConfiguration> WorkflowStepsConfigurations { get; set; }
    }
}
