//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentBarcodeMetadatas = new HashSet<DocumentBarcodeMetadata>();
            this.DocumentComments = new HashSet<DocumentComment>();
            this.DocumentsUserActions = new HashSet<DocumentsUserAction>();
            this.Indices = new HashSet<Index>();
            this.Pages = new HashSet<Page>();
        }
    
        public long Id { get; set; }
        public long BatchId { get; set; }
        public int DocumentType { get; set; }
        public System.DateTime Created { get; set; }
        public int Status { get; set; }
        public int Order { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual DocumentAssignment DocumentAssignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentBarcodeMetadata> DocumentBarcodeMetadatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentComment> DocumentComments { get; set; }
        public virtual DocumentQrMetadata DocumentQrMetadata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentsUserAction> DocumentsUserActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Index> Indices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages { get; set; }
    }
}
