//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentsUserAction
    {
        public int Id { get; set; }
        public long DocumentId { get; set; }
        public string Username { get; set; }
        public int DocumentAction { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
