//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstanceConfiguration
    {
        public int Id { get; set; }
        public string ConfigurationName { get; set; }
        public int Value { get; set; }
        public bool Active { get; set; }
    }
}
