//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAudit
    {
        public long Id { get; set; }
        public string Username { get; set; }
        public System.DateTime AttemptDate { get; set; }
        public bool IsLoginSuccessful { get; set; }
        public string Message { get; set; }
    }
}
