//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageQrMetadata
    {
        public long PageId { get; set; }
        public int PageNumber { get; set; }
        public int DocumentHandle { get; set; }
        public string Qrcode { get; set; }
    
        public virtual Page Page { get; set; }
    }
}
