//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public string Filename { get; set; }
        public int Order { get; set; }
        public Nullable<long> DocumentId { get; set; }
        public int Version { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Document Document { get; set; }
        public virtual PageQrMetadata PageQrMetadata { get; set; }
    }
}
