//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleWorkflowAssignment
    {
        public int RoleId { get; set; }
        public int WorkflowId { get; set; }
        public string QueuePermissions { get; set; }
    
        public virtual Workflow Workflow { get; set; }
    }
}
