//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesSpecialPermission
    {
        public int RoleId { get; set; }
        public bool HasWorkflowsAdministration { get; set; }
        public bool HasBatchesControl { get; set; }
        public bool HasReleaseBatches { get; set; }
        public bool HasDeleteBatches { get; set; }
        public bool HasRenameBatches { get; set; }
        public bool HasUnblockBatches { get; set; }
        public bool HasDeletePages { get; set; }
        public bool HasApproveAllDocuments { get; set; }
        public bool HasIndexOnSupervision { get; set; }
        public bool CanReleaseOnDigitalizationException { get; set; }
        public bool CanWorkWithRandomAssignation { get; set; }
    }
}
