//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannerProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScannerProfile()
        {
            this.RoleScannerProfilesAssignments = new HashSet<RoleScannerProfilesAssignment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProfileStatus { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Username { get; set; }
        public bool AutomaticBrightness { get; set; }
        public bool BothSides { get; set; }
        public bool AutomaticFeeding { get; set; }
        public bool AutomaticScan { get; set; }
        public int ImageQuality { get; set; }
        public int Resolution { get; set; }
        public bool AutoDetectedSize { get; set; }
        public bool SkipBlankPage { get; set; }
        public bool AutomaticAlignment { get; set; }
        public bool ScannerUi { get; set; }
        public bool ShowIndicator { get; set; }
        public int PixelTypeConfigurationId { get; set; }
        public int PaperSizeConfigurationId { get; set; }
    
        public virtual PaperSizeConfiguration PaperSizeConfiguration { get; set; }
        public virtual PixelTypeConfiguration PixelTypeConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleScannerProfilesAssignment> RoleScannerProfilesAssignments { get; set; }
    }
}
