//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workflow()
        {
            this.Batches = new HashSet<Batch>();
            this.RoleWorkflowAssignments = new HashSet<RoleWorkflowAssignment>();
            this.WorkflowDocumentTypeAssignments = new HashSet<WorkflowDocumentTypeAssignment>();
            this.ExternalProperties = new HashSet<ExternalProperty>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string AutoName { get; set; }
        public bool IsArchived { get; set; }
        public int VolumeId { get; set; }
        public int DocumentLimitPerBatchQuantity { get; set; }
        public int DocumentLimitPerBatchAlert { get; set; }
        public int PageLimitPerDocumentAlert { get; set; }
        public int PageLimitPerDocumentQuantity { get; set; }
        public string SpecialPermissions { get; set; }
        public bool HasAutomaticAssignmentForDocuments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
        public virtual DocumentsSplitter DocumentsSplitter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleWorkflowAssignment> RoleWorkflowAssignments { get; set; }
        public virtual Volume Volume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowDocumentTypeAssignment> WorkflowDocumentTypeAssignments { get; set; }
        public virtual WorkflowSplitter WorkflowSplitter { get; set; }
        public virtual WorkflowStepsConfiguration WorkflowStepsConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalProperty> ExternalProperties { get; set; }
    }
}
