//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowSplitter
    {
        public int WorkflowSplitterId { get; set; }
        public int ReaderColorMode { get; set; }
        public Nullable<int> ReaderTimeOut { get; set; }
        public int Orientation { get; set; }
        public float CoordinateX { get; set; }
        public float CoordinateY { get; set; }
        public float Width { get; set; }
        public float Height { get; set; }
        public string CodeFormat { get; set; }
        public string ExpectedValue { get; set; }
        public bool KeepPage { get; set; }
    
        public virtual Workflow Workflow { get; set; }
    }
}
