//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStepsConfiguration
    {
        public int WorkflowStepsConfigurationId { get; set; }
        public int QaScanScannedDocumentsPercent { get; set; }
        public int QaScanDocumentsApprovementPercent { get; set; }
        public int QaIndexScannedDocumentsPercent { get; set; }
        public int QaIndexDocumentsApprovementPercent { get; set; }
        public int IndexingNumbers { get; set; }
        public bool HasIndexSupervision { get; set; }
        public bool HasExternalValidation { get; set; }
    
        public virtual Workflow Workflow { get; set; }
    }
}
