//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowDocumentTypeAssignment
    {
        public int WorkflowId { get; set; }
        public int DocumentTypeId { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual Workflow Workflow { get; set; }
    }
}
